language: r



sudo: required

dist: trusty

notifications:
  email:
    recipients:
      - zheng.bangyou@gmail.com
    on_success: always
    on_failure: always

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended
install:
   - sudo apt-get install -y libgdal1-dev
   - Rscript -e "if (!require('devtools')) install.packages('devtools')"
   - Rscript -e "if (!require('geosphere')) install.packages('geosphere')"
   - Rscript -e "if (!require('rsconnect')) install.packages('rsconnect')"
   - Rscript -e "if (!require('sp')) install.packages('sp')"
   - Rscript -e "if (!require('shiny')) install.packages('shiny')"
   - Rscript -e "if (!require('shinydashboard')) install.packages('shinydashboard')"
   - Rscript -e "if (!require('leaflet')) devtools::install_github('byzheng/leaflet')"
   - Rscript -e "if (!require('leafletplugins')) devtools::install_github('byzheng/leafletplugins')"
   - Rscript -e "if (!require('dplyr')) install.packages('dplyr')"
   - Rscript -e "if (!require('tidyr')) install.packages('tidyr')"
   - Rscript -e "if (!require('readr')) install.packages('readr')"
   - Rscript -e "if (!require('knitr')) install.packages('knitr')"
   - Rscript -e "if (!require('caTools')) install.packages('caTools')"
   - Rscript -e "if (!require('rgeos')) install.packages('rgeos')"
   - Rscript -e "if (!require('rgeos')) install.packages('rgdal')"
   - Rscript -e "if (!require('rmarkdown')) install.packages('rmarkdown')"

script:
  - Rscript _build.R ${SHINY_TOKEN} ${SHINY_SECRET}

cache:
  packages: yes


